### ISSUE TITLE
cargo-geiger detection

### ISSUE THREAD

**Issue by tarcieri** [mxxo/plutonium#1]
Work is underway to add proc macro expansion to `cargo-geiger`.

It'd be interesting if `plutonium` could detect that it's being run under `cargo-geiger` and only emit safe code in such a case (possibly using `optimize!`)

**Comment by mxxo** [comment]
I've definitely considered if this is feasible. You might want to hide in debug builds and only surface in release builds (release builds might be expensive, etc). Then, you could try `#[cfg(debug_assertions)]` (sort of the reverse of what [fake-static](https://github.com/NieDzejkob/fake-static/blob/8f3ea2c13f189d8e89ecd2ffa9cb056d37575dc9/src/lib.rs#L3-L4) does). This won't reliably detect that you're in release mode though, because you could have a cargo release profile with debug assertions [turned on](https://doc.rust-lang.org/cargo/reference/profiles.html#debug-assertions). From there maybe you could try parsing the build command and decide.

In the end though I think `cargo-geiger` is a cool and useful tool, and I don't want to be antagonistic.
